# 該配置檔即應用在開發環境下都應該獲取的參數
log:
  file:
    path: ./logs
    max:
      history: 5
      size: 100
  charset:
    console: UTF-8
    file: utf-8


datasource:
  maria:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://192.168.1.110:3306/SpringBootTemplate?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 74e4ff9494674aeaa99e554ff2082961
    idle-timeout: 1000
    connection-timeout: 5000
    connection-test-query: SELECT 1